// This is just specifying a name for the workflow
name: CI

// The on command is used to specify an event that will trigger the workflow, this event can be push, pull_request, etc. 
//It can also be an array of events like this.
on: [push] 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.